[package]
name = "podlet"
version = "0.1.0"
authors = ["Paul Nettleton <k9@k9withabone.dev>"]
edition = "2021"
description = "Podlet generates podman quadlet (systemd-like) files from a podman command."
readme = "README.md"
repository = "https://github.com/k9withabone/podlet"
license = "MPL-2.0"
keywords = ["podman", "quadlet"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
color-eyre = "0.6.2"
ipnet = "2.7.2"
shlex = "1.1.0"
thiserror = "1.0.40"
url = "2.3.1"
